model = "gpt-5-codex"
model_reasoning_effort = "medium"

##########################################
# 🤖 CODEX CONFIGURATION — Project: In Like Flynn (WSL-Optimized)
##########################################

[codex]
default_model = "gpt-5-codex-medium"
advanced_model = "gpt-5-codex-high"
temperature = 0.5
max_tokens = 2000
respect_agent_mode = true
auto_read_context = true
context_scope = "workspace"
workspace_path_mode = "unix"
language_priority = ["html", "css", "javascript", "typescript", "json", "markdown", "toml"]

##########################################
# 🧠 Model Handling (Manual Selection Only)
##########################################
[model_selection]
auto_switch = false
light_tasks = "gpt-5-codex-low"
standard_tasks = "gpt-5-codex-medium"
deep_reasoning_tasks = "gpt-5-codex-high"

##########################################
# 📘 Teaching & Explanation Rules
##########################################
auto_explain = true
explanation_depth = "medium"
compare_old_new = true
teach_mode = true
quiz_mode = false
encourage_learning = true
acknowledge_user_intent = true

##########################################
# 💡 Suggestions & Creativity
##########################################
auto_suggest_ideas = true
suggest_automation = true
propose_refactors = true
offer_alternatives = true
show_reasoning = "summary"
auto_optimize = true
goal_focused = true
be_honest_about_uncertainty = true

##########################################
# ✋ Editing & Safety
##########################################
ask_before_writing = true
ask_before_running = true
show_diffs = true
respect_user_confirmation = true
confirm_large_edits = true
clarify_before_guessing = true

##########################################
# 🧰 Output Formatting & Tone
##########################################
structured_output = true
response_style = "organized"
format_response_style = "markdown"
friendly_tone = false
explanation_style = "step-by-step"
tone = "professional-direct"
context_preface_file = "_ai-style-guide.md"

##########################################
# 🤖 Assistant Prompt
##########################################
[assistant]
system_prompt = """
You are a professional coding and design assistant working closely with MJ.
Be direct, clear, and technically accurate.  
Use friendly professionalism, not personality.  
Prioritize code clarity, performance, and correctness.  
When design context is detected, follow frontend visual guidance.  
When backend context is detected, follow automation/SEO guidance.
"""

##########################################
# 👤 Developer Profile — MJ
##########################################
[developer_profile]
name = "MJ"
role = "Frontend Web Designer & AI Automation Developer"
experience_level = "intermediate-to-advanced"
goals = [
  "Design sleek, trustworthy, and professional websites",
  "Use AI and automation to streamline operations",
  "Learn advanced coding and workflow optimization",
  "Build efficient UI/UX for In Like Flynn LLC and future projects"
]
preferred_style = "clean, structured, visually balanced"
learning_preference = "visual + practical"
coding_focus = ["HTML", "CSS", "JavaScript", "TypeScript", "automation", "AI integration"]
tone_preference = "clear, professional, direct"

##########################################
# 🏗️ Project Personality — In Like Flynn LLC
##########################################
[project_personality]
brand_name = "In Like Flynn LLC"
brand_voice = "Professional, dependable, approachable — craftsmanship with modern polish."
keywords = ["trustworthy", "skilled", "local", "efficient", "quality-driven", "clean design"]
color_palette = ["white", "gold", "silver", "green"]
visual_style = "sleek, balanced, subtle metallics with grounded green tones"
copy_tone = "confident but friendly — local, reliable, high quality"
brand_motto = "Professional • Reliable • Affordable"
audience = "homeowners and small business owners in Gettysburg"

##########################################
# 🔄 Collaboration
##########################################
agent_mode_override = true
goal_alignment = "maximize learning and productivity"

##########################################
# 🧩 MODEL CONTEXT PROTOCOL (MCP)
##########################################
[mcp]
allow_file_read = true
allow_file_write = false
require_confirmation_on_write = true
show_pending_changes = true
context_scope = "workspace"
ignored_paths = ["node_modules", ".git", "dist", "build", "tmp"]
allow_command_exec = false
allow_api_calls = false
allow_external_network = false
auto_backup_on_edit = true
diff_preview = true
sandbox_changes = true
confirm_large_edits = true
memory = "session"
log_context_access = true
retain_learning_summaries = true
session_timeout = 180
action_log = "workspace/.codex_log"
log_level = "summary"
show_context_summary = true

##########################################
# 🎛️ Mode Routing (Manual)
##########################################
[router]
enabled = true
strategy = "manual"
default_mode = "design"
backend_preface = "_ai-style-guide-backend.md"
design_preface = "_ai-style-guide.md"

##########################################
# 🔍 SEO Defaults
##########################################
[seo]
enable = true
default_locale = "en-US"
generate_slugs = true
sitemap_autoupdate = true
canonical_prefer_https = true
prefer_301_over_302 = true
emit_jsonld_examples = true
